version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Adjust if your requirements.txt or pyproject.toml is in a subdirectory
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
